<?php
/**
 * Lesti_Version (http:gordonlesti.com/lestiversion)
 *
 * PHP version 5
 *
 * @link      https://github.com/GordonLesti/Lesti_Version
 * @package   Lesti_Fpc
 * @author    Gordon Lesti <info@gordonlesti.com>
 * @copyright Copyright (c) 2013-2014 Gordon Lesti (http://gordonlesti.com)
 * @license   http://opensource.org/licenses/OSL-3.0 Open Software License (OSL 3.0)
 */
?>
<script type="text/javascript">
    var oldVersion = <?php echo $this->getOld() ?>;
    var newVersion = <?php echo $this->getNew() ?>;
    var Versions = Class.create({
        initialize: function() {
            $$('input.version_radio').each(
              function(link) {
                  Event.observe(link, 'click', this.request.bindAsEventListener(this, link));
              }.bind(this)
            );
        },

        request: function(event, link) {
            var objectId = link.id;
            if(objectId.substring(0,12) == 'old_version_') {
                oldVersion = parseInt(objectId.substring(12));
                $$('input.version_radio').each(
                    function(input) {
                        if(input.id.substring(0,12) == 'new_version_') {
                            var newV = parseInt(input.id.substring(12));
                            if(oldVersion > newV) {
                                input.disable();
                            } else {
                                input.enable();
                            }
                        }
                    }
                );
            }
            if(objectId.substring(0,12) == 'new_version_') {
                newVersion = parseInt(objectId.substring(12));
                $$('input.version_radio').each(
                    function(input) {
                        if(input.id.substring(0,12) == 'old_version_') {
                            var oldV = parseInt(input.id.substring(12));
                            if(newVersion < oldV) {
                                input.disable();
                            } else {
                                input.enable();
                            }
                        }
                    }
                );
            }
            url = "<?php echo $this->getUrl('adminhtml/version_diff/cmsblock')?>";
            url += "old/"+oldVersion+"/new/"+newVersion+"/";
            new Ajax.Request(url, {
                method: 'get',
                onSuccess: function(transport) {
                    if(transport && transport.responseText) {
                        try{
                            response = eval('('+transport.responseText+')');
                        }
                        catch (e) {
                            response = {};
                        }
                        if(response.table) {
                            $('version_table').update(response.table);
                        }
                    }
                }.bind(this)}
            );
        }
    });

    Event.observe(window, 'load', function() {
       versions = new Versions();
    });
</script>